sudo: false
language: ruby
cache: bundler
rvm:
  - 2.2.0
script:
  - "echo \"---\"  > ~/.gem/credentials"
  - "echo \":rubygems_api_key: $RUBYGEMS_API_KEY\" >> ~/.gem/credentials"
  - chmod 0600 ~/.gem/credentials
  - gem build git-amend.gemspec
  - gem push git-amend-*.gem
  - rm -f ~/.gem/credentials
